title: Hari's Docs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"  
