site_name: Hari's Books
site_url: https://havenkat.github.io/
site_author: Hari P Venkateshaiah

nav:
  - Rust:
      - books/rust.md
  - Authorization:
      - Concepts: books/authz.md
      - Mutual Auth: books/mtls.md 

theme: readthedocs