site_name: Hari's Books
site_url: https://havenkat.github.io/

nav:
  - Home: index.md
  - Rust: books/rust.md
  - Authorization:
      - Concepts: books/authz.md
      - Mutual Auth: books/mtls.md 
      - Cedar: books/cedar.md
