name: Hari's Docs
title: Havenkat Books
show_downloads: false

navigation:
  - title: "Home"
    url: ./README.md
    internal: true
  - title: "Authorization"
    url: ./books/authz.md
    internal: true
  - title: "First Page"
    url: /docs/first_page.md
  - title: "Second Page"
    url: /docs/second_page.md


markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-default-layout
  - jekyll-paginate
  - jekyll-paginate-content
