name: Hari's Docs
title: Havenkat books
show_downloads: false
theme: "just-the-docs"

navigation:
  - title: "Home"
    url: ./README.md
  - title: "Authorization"
    url: ./books/authz.md
  - title: "First Page"
    url: /docs/first_page.md
  - title: "Second Page"
    url: /docs/second_page.md


markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"

plugins:
  - jekyll-paginate
  - jekyll-paginate-content
