name: Hari's Docs
title: Havenkat books
show_downloads: false

menu:
  - title: Home
    url: /
  - title: Authorization
    url: books/authz.md


markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"

plugins:
  - jekyll-paginate
  - jekyll-paginate-content
